import Header from "@/components/layout/Header";
import SavedJobsProvider from "@/contexts/SavedJobsProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "@/contexts/ThemeContextProvider";
import UserContextProvider from "@/contexts/UserContextProvider";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeContextProvider>
          <UserContextProvider>
            <SavedJobsProvider>
              <Header />
              {children}
              <Footer />
            </SavedJobsProvider>
          </UserContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
